[package]
name = "tinymarch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
nalgebra = "0.31.1"
rand = "0.8.5"
rayon = "1.7.0"